name: Security Audit
on:
    schedule:
        - cron: 0 0 1,15 * *
    push:
        paths:
            - '**/Cargo.toml'

jobs:
    security_audit:
        runs-on: ubuntu-latest
        if: github.actor != 'sbosnick-bot'
        steps:
            - name: Checkout
              uses: actions/checkout@v1
            - name: Audit
              uses: actions-rs/audit-check@v1
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
